# Generated by Django 4.2.16 on 2024-10-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('memmbership_number', models.CharField(max_length=50, unique=True, verbose_name='Номер абонемента')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('memmbership_type', models.CharField(max_length=50, verbose_name='Вид абонемента')),
                ('memmbership_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена абонемента')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('start_date', models.DateField(verbose_name='Начало действия абонемента')),
                ('end_date', models.DateField(verbose_name='Конец действия абонемента')),
            ],
        ),
    ]
