# Generated by Django 4.2.16 on 2024-11-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('subscription_end', 'Окончание абонемента'), ('birthday', 'День рождения')], max_length=50),
        ),
    ]
